import Home from "./Home";
import About from "./About";
import Gymbanner from "./Gymbanner";
import Login from "./Login";
import Register from "./Register";
import ConfigAdminUser from "./ConfigAdminUser";
import CreateClass from "./CreateClass";
import Profile from "./Profile";
import UserIndex from "./UserIndex";
import GymProfile from "./GymProfile";
import AdminPage from "./AdminPage";

export { Home }
export { About }
export { Gymbanner }
export { Login }
export { Register }
export { ConfigAdminUser }
export { CreateClass }
export { Profile }
export { UserIndex }
export { GymProfile }
export { AdminPage }